### ISSUE TITLE
Multiple problems building darwin_studio

### ISSUE THREAD

**Issue by JJ** [tlemo/darwin#3]
Long story short, I haven't managed to build it. I downloaded QT Studio, and installed it as an user. I open it, but then
1. `darwin_studio` does not show up as a subproject of darwin_pro, so I can't select it.
2. I open darwin_studio.pro from its own directory, I try to compile, but then I get this error
![Captura de pantalla de 2021-02-09 12-26-49](https://user-images.githubusercontent.com/500/107357388-464c1600-6ad2-11eb-9799-44bde43abe44.png). I install it using `apt` but it does not seem to find it.
3. I would try building from the command line, but I really have no idea where the Qt installer for Linux installs that kind of thing, or what that would actually be building.

Any way, I'm going to see if the last point is easy to figure out and will try that. Also not clear what this is intended for. Do we need this for darwin, or just for Darwin studio?

**Comment by JJ** [comment]
OK, quick update here: I've found Qt Charts in GitHub, downloaded it, and tried to compile it... But then 

```
Project ERROR: Unknown module(s) in QT: openglwidgets
```

Baseline is: I don't think this works with Qt6. Let's try the other version...

**Comment by JJ** [comment]
Finally managed to build it downgrading to the last version of 5.x.x. You might want to clarify that.

**Comment by tlemo** [comment]
Hi @JJ , thanks for reporting the build issues with Qt 6.x. I've updated the setup instructions to warn that Qt 6.x is not yet supported.
